import type { Slot, SlotId } from '@/types';

/**
 * Die sechzehn Bildplaetze aus docs/03-BILDBRIEFINGS.md als Datenstruktur.
 * Fehlt `file`, rendert Figure die gestaltete Materialflaeche mit Slot-Kennung.
 * Seitenverhaeltnis, Crop und Bewegung sind in beiden Faellen identisch,
 * deshalb aendert der spaetere Bildeintritt nichts am Layout.
 */
export const slots: Record<SlotId, Slot> = {
  'obj-01': { id: 'obj-01', klasse: 'objekt', material: 'haus', priority: 'lazy', motion: 'parallax-6',
    ratio: { desktop: '16/9', mobile: '4/5' },
    motiv: 'Leitmotivhaus im Bestand, altes Dach, Moos in den Kehlen, Straßenansicht',
    alt: 'Freistehendes Wohnhaus mit Satteldach aus rotbraunen Tondachziegeln, Dachfläche mit Moosbildung, Aufnahme von der Straßenseite.' },
  'obj-02': { id: 'obj-02', klasse: 'objekt', material: 'ziegel', priority: 'lazy', motion: 'parallax-8',
    ratio: { desktop: '21/9', mobile: '3/2' },
    motiv: 'Dachfläche aus erhöhter Position, Ziegelreihen im Streiflicht',
    alt: 'Dachfläche mit Ziegelreihen im Streiflicht, First, Gratkante und Blechanschluss am Kamin.' },
  'obj-03': { id: 'obj-03', klasse: 'objekt', material: 'modul', priority: 'lazy', motion: 'parallax-6',
    ratio: { desktop: '16/9', mobile: '4/5' },
    motiv: 'Leitmotivhaus fertig, neues Ziegeldach mit Photovoltaikanlage, identische Achse wie obj-01',
    alt: 'Dasselbe Wohnhaus nach der Sanierung, neues Ziegeldach mit geschlossenem Photovoltaikfeld und gleichmäßigen Randabständen.' },
  'obj-04': { id: 'obj-04', klasse: 'objekt', material: 'landschaft', priority: 'eager', motion: 'parallax-4',
    ratio: { desktop: '16/9', mobile: '3/4' },
    motiv: 'Himmel im frühen Morgen und Landschaftsband für die Hero-Szene',
    alt: '' },
  'mat-01': { id: 'mat-01', klasse: 'material', material: 'ziegel', priority: 'eager', motion: 'parallax-6',
    ratio: { desktop: '4/5', mobile: '3/2' },
    motiv: 'Tondachziegel im Streiflicht, Doppelmuldenfalz, drei bis vier Reihen',
    alt: 'Nahaufnahme einer Dachfläche aus Tondachziegeln im Doppelmuldenfalz, Streiflicht betont die Profilkanten.' },
  'mat-02': { id: 'mat-02', klasse: 'material', material: 'modul', priority: 'eager', motion: 'parallax-6',
    ratio: { desktop: '4/5', mobile: '3/2' },
    motiv: 'Modulkante mit Aluminiumrahmen und ruhiger Himmelsreflexion',
    alt: 'Kante eines Photovoltaikmoduls mit Aluminiumrahmen, Zellstruktur und ruhiger Himmelsreflexion im Glas.' },
  'mat-03': { id: 'mat-03', klasse: 'material', material: 'zink', priority: 'lazy', motion: 'mask',
    ratio: { desktop: '3/2', mobile: '1/1' },
    motiv: 'Blechanschluss am Kamin, sauber gefalzte Kante',
    alt: 'Sauber gefalzter Zinkblechanschluss am Übergang zwischen Kamin und Ziegeldeckung.' },
  'mat-04': { id: 'mat-04', klasse: 'material', material: 'holz', priority: 'lazy', motion: 'mask',
    ratio: { desktop: '3/2', mobile: '4/5' },
    motiv: 'Offener Dachaufbau, Sparren, Dämmung, Unterdeckung, Lattung',
    alt: 'Offener Dachaufbau mit Sparren, Zwischensparrendämmung, Unterspannbahn und Lattung.' },
  'mat-05': { id: 'mat-05', klasse: 'material', material: 'modul', priority: 'lazy', motion: 'mask',
    ratio: { desktop: '16/9', mobile: '4/5' },
    motiv: 'Wechselrichter und Speicher im Hausanschlussraum, saubere Kabelführung',
    alt: 'Wechselrichter und Batteriespeicher mit sauberer Kabelführung an einer Kellerwand.' },
  'pro-01': { id: 'pro-01', klasse: 'prozess', material: 'ziegel', priority: 'lazy', motion: 'parallax-4',
    ratio: { desktop: '3/2', mobile: '4/5' },
    motiv: 'Hände legen einen Ziegel in die Lattung, Werkzeug im Bild, kein Blick in die Kamera',
    alt: 'Hände legen einen Dachziegel in die Lattung ein, Werkzeug liegt daneben.' },
  'pro-02': { id: 'pro-02', klasse: 'prozess', material: 'holz', priority: 'lazy', motion: 'mask',
    ratio: { desktop: '3/2', mobile: '1/1' },
    motiv: 'Bestandsaufnahme im Dachraum, Messgerät am Sparren',
    alt: 'Prüfung im Dachraum, eine Hand hält ein Messgerät an den Sparren.' },
  'pro-03': { id: 'pro-03', klasse: 'prozess', material: 'haus', priority: 'lazy', motion: 'mask',
    ratio: { desktop: '3/2', mobile: '4/5' },
    motiv: 'Planung am Tisch, Dachaufsicht als Zeichnung, Hand mit Stift',
    alt: 'Dachaufsicht als Zeichnung auf einem Tisch, eine Hand trägt die Modulbelegung ein.' },
  'pro-04': { id: 'pro-04', klasse: 'prozess', material: 'modul', priority: 'lazy', motion: 'parallax-6',
    ratio: { desktop: '21/9', mobile: '3/4' },
    motiv: 'Modulmontage auf der Schiene, zwei Personen im Anschnitt, Sicherung sichtbar',
    alt: 'Zwei Handwerker setzen ein Photovoltaikmodul auf die Montageschiene eines Ziegeldachs.' },
  'pro-05': { id: 'pro-05', klasse: 'prozess', material: 'haus', priority: 'lazy', motion: 'parallax-4',
    ratio: { desktop: '3/2', mobile: '4/5' },
    motiv: 'Gespräch am Objekt, zwei Personen von hinten, Blick zum Dach',
    alt: 'Zwei Personen stehen vor einem Wohnhaus und betrachten die Dachfläche, eine deutet nach oben.' },
  'reg-01': { id: 'reg-01', klasse: 'region', material: 'landschaft', priority: 'lazy', motion: 'parallax-4',
    ratio: { desktop: '21/9', mobile: '16/9' },
    motiv: 'Leinebergland, Fernblick über Felder auf eine Ortschaft im Morgendunst',
    alt: 'Blick über die Landschaft des Leineberglands, im Hintergrund die Dächer einer Ortschaft im Morgendunst.' },
  'reg-02': { id: 'reg-02', klasse: 'region', material: 'haus', priority: 'eager', motion: 'parallax-6',
    ratio: { desktop: '16/9', mobile: '3/2' },
    motiv: 'Straßenzug mit gemischter Bebauung und unterschiedlichen Dachformen',
    alt: 'Straßenzug mit unterschiedlichen Dachformen, im Hintergrund ein Dach in Sanierung.' },
};

export const slot = (id: SlotId): Slot => slots[id];
